server:
  port: 8889
  address: 0.0.0.0
  tomcat:
    max-http-post-size: 20971520

spring:
  datasource:
    url: jdbc:mysql://47.100.79.118:3306/201911a?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: eyJhbGciOiJIUzI1NiJ9
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true

